# Generated by Django 5.2.5 on 2025-08-22 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('operating_system', models.CharField(blank=True, default='', max_length=255)),
                ('processor', models.CharField(blank=True, default='', max_length=255)),
                ('num_cores', models.IntegerField(default=0)),
                ('num_threads', models.IntegerField(default=0)),
                ('ram_total', models.BigIntegerField(default=0)),
                ('ram_used', models.BigIntegerField(default=0)),
                ('ram_available', models.BigIntegerField(default=0)),
                ('storage_total', models.BigIntegerField(default=0)),
                ('storage_used', models.BigIntegerField(default=0)),
                ('storage_free', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cpu_usage', models.FloatField(blank=True, help_text='percent', null=True)),
                ('memory_usage', models.FloatField(blank=True, help_text='MB', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='core.host')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.process')),
            ],
        ),
        migrations.DeleteModel(
            name='ProcessInfo',
        ),
        migrations.DeleteModel(
            name='SystemInfo',
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['host', 'pid'], name='core_proces_host_id_77df9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('host', 'pid')},
        ),
    ]
